[package]
name = "bybit-rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"
categories = ["api-bindings"]
description = "Bybit V5 API bindings in Rust"

[lib]
name = "bybit_rs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.111"
error-chain = { version = "0.12.4", default-features = false }
itertools = "0.12.0"

